### ISSUE TITLE
Docker Compose hostname

### ISSUE THREAD

**Issue by soon530** [soon530/docker-study#13]
如果沒有設定hostname的話，就是隨便給你。

```
version: '3.6'
services:

  home-mysql57:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
```

```
# hostname
85b96944936c
```
