### ISSUE TITLE
Docker Compose Nginx

### ISSUE THREAD

**Issue by soon530** [soon530/docker-study#14]
使用mac在本地端完成反向代理。

要設定
1. docker-compose.yml
2. nginx config

**Comment by soon530** [comment]
docker-compose.ym設定。

nginx 
  -> api-php56(api.example.com)
  -> home-php74(home.example.com)

只有nginx要mac:80->container:80
api-php56只有container:80
home-php74只有container:80

也就是說，mac沒辦法直接運api-php56及home-php74，要透過nginx才行。

```
version: '3.6'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api-php56
      - home-php74

  api-php56:
    depends_on:
      - api-mysql55
    image: php:5.6-apache
    volumes:
      - "./api:/var/www/html"
    expose:
      - "80"
    hostname: api-php56
    environment:
      - VIRTUAL_HOST=api.example.com

  home-php74:
    depends_on:
      - home-mysql57
    image: php:7.4-apache
    volumes:
      - "./home:/var/www/html"
    expose:
      - "80"
    hostname: home-php74
    environment:
      - VIRTUAL_HOST=home.example.com
```
