### ISSUE TITLE
docker compose volumes的命名規則？

### ISSUE THREAD

**Issue by soon530** [soon530/docker-study#34]
mysql資料先放在一個叫`data`的volume

有個`docker-compose.yml`放在`vic`資料夾下

```
vic
 - docker-compose.yml
```

```
version: '3.6'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - 'data:/var/lib/mysql'
    ports:
      - "3307:3306"

volumes:
  data:
```

**Comment by soon530** [comment]
這樣不行，會產生`vic_data`的volume。

```
version: '3.6'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - 'data:/var/lib/mysql'
    ports:
      - "3307:3306"

volumes:
  data:
```

**Comment by soon530** [comment]
要指定名稱，才不會被偷加上目錄名稱。

```
version: '3.6'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - 'data:/var/lib/mysql'
    ports:
      - "3307:3306"

volumes:
  data:
  name: data
```
